name: finance_copilot
version: "1.0"
config-version: 2

profile: finance_copilot

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]
test-paths: ["dbt/tests"]

target-path: "dbt/target"
clean-targets:
  - "dbt/target"
  - "dbt/dbt_modules"

vars:
  csv_base_path: "clean_data"

models:
  finance_copilot:
    +persist_docs:
      relation: true
      columns: true
    +materialized: table
    +database: duckdb_finance

    raw:
      +materialized: table

    staging:
      +materialized: table

    marts:
      +materialized: table
