[project]
name = "finance-copilot"
version = "0.1.0"
description = ""
authors = [
    {name = "williamfohara",email = "billlyoharaa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai (>=1.93.3,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "intuit-oauth (>=1.2.6,<2.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "uvicorn (>=0.35.0,<0.36.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
