version: 2

sources:
  - name: qbo_raw # 👈 Must match the name in your dbt models
    schema: main
    tables:
      - name: qbo_account_list
        external:
          location: "clean_data/qbo_account_list.csv"
          format: csv
          options:
            header: true
      - name: qbo_balance_sheet
        external:
          location: "clean_data/qbo_balance_sheet.csv"
          format: csv
          options:
            header: true
      - name: qbo_general_ledger
        external:
          location: "clean_data/qbo_general_ledger.csv"
          format: csv
          options:
            header: true
      - name: qbo_pl
        external:
          location: "clean_data/qbo_pl.csv"
          format: csv
          options:
            header: true

models:
  - name: stg_account_list
    columns:
      - name: account_name
        tests: [not_null]
      - name: balance
        tests:
          - not_null
          - accepted_values:
              values: ["0", "1", "2"]
              config:
                severity: warn

  - name: stg_general_ledger
    columns:
      - name: txn_date
        tests: [not_null]
      - name: amount
        tests: [not_null]
